### ISSUE TITLE
Upgrading to to 0.10.0 breaks Rails.env?

### ISSUE THREAD

**Issue by samstickland** [trailblazer/cells-haml#4]
Hi,

I've just upgraded from 0.0.8 to 0.0.10 and now I get errors when I try to access Rails.env from inside a cell:

      Failure/Error: Rails.env.test? ? 'Add' : raw('<i class="icon-plus"></i>')

      NoMethodError:
        undefined method `env' for Cell::Haml::Rails:Module

Dropping back to down 0.0.8 works for me.

(This strange bit of code is because trying to click a link made entirely from an icon-moon font fails on Codeship).

**Comment by timoschilling** [comment]
Change your code to `::Rails.env.test? ? 'Add' : raw('<i class="icon-plus"></i>')`

**Comment by samstickland** [comment]
Ah gotcha. It's because it was resolving to this new module?

https://github.com/trailblazer/cells-haml/blob/41c9d481e2b91366e386f18c264ce9d599b01db5/lib/cell/haml/rails.rb

2016-05-01 16:19 GMT+01:00 Timo Schilling <notifications@github.com>:

**Comment by timoschilling** [comment]
Yes, thats the reason.
