### ISSUE TITLE
Rails 5

### ISSUE THREAD

**Issue by dgilperez** [trailblazer/cells-haml#6]
Hi!

I'm trying to upgrade my Rails 4 / Cells 3 app to Rails 5.

When I upgrade `cells` to 4.1 and add `cells-haml` to 0.0.10, the latter is requiring `haml` to be greater than 4.1.0.beta.1. That is conflicting with latest stable `haml-rails` (requiring ~> 4.0.0), which I believe is a common way to add haml support to a Rails app. At this point I'm not sure is worth it to keep digging. 

So, my question: is cells 4.1 ready for Rails 5 / Is it been used in production? If so, what's a common setup to include haml?

Thanks a lot and sorry for the confusion.

**Comment by apotonick** [comment]
Hi, you can simply use hamlit, it's better, faster, cleaner. I don't know when/if they will fix Haml - this is a bug in Haml, not in Cells.

**Comment by dgilperez** [comment]
Hamlit is a great suggestion, thanks for the introduction.
