### ISSUE TITLE
Update the README about haml to `5.0.0.beta.2`?

### ISSUE THREAD

**Issue by PikachuEXE** [trailblazer/cells-haml#8]
Or just ask them to try

**Comment by apotonick** [comment]
Does that version play nicely with Cells?

**Comment by PikachuEXE** [comment]
The only issue I can think of is the HTML escaping (especially when using form helpers)
And it looks fine to me
But this can wait for 5.0.0 release first

**Comment by apotonick** [comment]
Ah ok, so my fixes from like 3 years ago were actually merged into 5.0?

**Comment by PikachuEXE** [comment]
Not sure what changes are you referring to :P

**Comment by seuros** [comment]
We drop support for haml 4.x , it was never released.
